provider:
  name: openfaas
  gateway: http://127.0.0.1:19999

functions:
  echo:
    lang: dockerfile
    handler: ./echo
    image: functions/faas-echo:latest
  dog:
    lang: dockerfile
    handler: ./Tester/dog
    image: functions/faas-dog:latest
    secrets:
      - secret-password
  hello-openfaas:
    lang: python3
    handler: ./hello-openfaas
    image: hello-openfaas:latest
