version: '3'
services: 
  web:
    restart: always
    build: .
    volumes: 
      - './www:/var/www/html'
    ports:
      - '27465:80'
  db:
    restart: always
    image: mariadb
    volumes:
      - './setup.sql:/docker-entrypoint-initdb.d/setup.sql'
    environment:
      MYSQL_ROOT_PASSWORD: 'db_password'
      MYSQL_DATABASE: 'db_test'
      MYSQL_USER: 'db_user'
      MYSQL_PASSWORD: 'db_password'
    ports: 
      - "3306:3306"
